api/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
//session_start();

Route::get('/', function()
{
	return View::make('hello');
});

Route::get('/api/test', function()
{
	//$email = Auth::user();
	//print_r($_SESSION['user']['id']);
	print_r(wp_get_current_user());

});


Route::any('/api/login', 'BaseController@login');

// =========== WORDPRESS =================
Route::resource('api/wp/posts', 'WpPostsController');
//Route::resource('api/wpposts', 'WpPostsController');


Route::get('/api/test_cmd', function(){
	$linuxService = new LinuxServices();
	$linuxService->executeCommand();
});

api/app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() != Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

api/app/models/User.php
<?php

// use Illuminate\Auth\UserTrait;
// use Illuminate\Auth\UserInterface;
// use Illuminate\Auth\Reminders\RemindableTrait;
// use Illuminate\Auth\Reminders\RemindableInterface;

// class User extends Eloquent implements UserInterface, RemindableInterface {

// 	use UserTrait, RemindableTrait;

// 	/**
// 	 * The database table used by the model.
// 	 *
// 	 * @var string
// 	 */
// 	protected $table = 'users';

// 	/**
// 	 * The attributes excluded from the model's JSON form.
// 	 *
// 	 * @var array
// 	 */
// 	protected $hidden = array('password', 'remember_token');

// }



class User extends Eloquent {

    // WordPress uses differently named fields for create and update fields than Laravel does
    const CREATED_AT = 'post_date';
    const UPDATED_AT = 'post_modified';
    
    // Set the table including database prefix used in WordPress
    protected $table = 'wp_users';

    // WordPress uses uppercase "ID" for the primary key
    protected $primaryKey = 'ID';

    // Hide the user_pass field
    protected $hidden = array('user_pass');

    // Whenever the user_pass field is modified, WordPress' internal hashing function will run
    public function setUserPassAttribute($pass)
    {
        $this->attributes['user_pass'] = wp_hash_password($pass);
    }

}

api/app/models/WpPost.php
<?php

class WpPost extends Eloquent {
	protected $guarded = array();
	protected $primaryKey = 'ID';
	public static $rules = array(
		'post_author' => 'required',
		'post_date' => 'required',
		'post_title' => 'required',
		'post_content' => 'required',
		'post_status' => 'required',
		'comment_status' => 'required',
		'menu_order' => 'required',
		'post_type' => 'required',
		'comment_count' => 'required'
	);
}

api/app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}



	protected function login(){

		//$creds = array('user_email' => Input::get('email'), 'laravel_pass' => Input::get('password'));
		$userdata = array(
		    'user_login' 	=> Input::get('log'),
		    'password' 		=> Input::get('pwd')
		);

		if (Auth::attempt($userdata))
		{
		    // successfully logged in
		    //print_r();
		    
			Auth::loginUsingId(Auth::user()->ID);
			$_SESSION['user']['id'] = Auth::user()->ID;
		    return 'Logged in';
		}
		else
		{
		    // authentication failed
		    return "authentication failed";
		}

		

	}

}

api/app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

api/app/controllers/WpPostsController.php
<?php

class WpPostsController extends BaseController {

	/**
	 * WpPost Repository
	 *
	 * @var WpPost
	 */
	protected $WpPost;

	public function __construct(WpPost $WpPost)
	{
		$this->WpPost = $WpPost;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$WpPosts = $this->WpPost->all();

		return View::make('WpPosts.index', compact('WpPosts'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('WpPosts.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, WpPost::$rules);

		if ($validation->passes())
		{
			$this->WpPost->create($input);

			return Redirect::route('api.wp.posts.index');
		}

		return Redirect::route('WpPosts.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$WpPost = $this->WpPost->findOrFail($id);

		return View::make('WpPosts.show', compact('WpPost'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$WpPost = $this->WpPost->find($id);

		if (is_null($WpPost))
		{
			return Redirect::route('api.wp.posts.index');
		}

		return View::make('WpPosts.edit', compact('WpPost'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, WpPost::$rules);

		if ($validation->passes())
		{
			$WpPost = $this->WpPost->find($id);
			$WpPost->update($input);

			return Redirect::route('api.wp.posts.show', $id);
		}

		return Redirect::route('api.wp.posts.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->WpPost->find($id)->delete();

		return Redirect::route('api.wp.posts.index');
	}

}

api/app/views/WpPosts/create.blade.php
@extends('layouts.scaffold')

@section('main')

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <h1>Create WpPost</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::open(array('route' => 'api.wp.posts.store', 'class' => 'form-horizontal')) }}

        <div class="form-group">
            {{ Form::label('post_author', 'Post_author:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_author', Input::old('post_author'), array('class'=>'form-control', 'placeholder'=>'Post_author')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_date', 'Post_date:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_date', Input::old('post_date'), array('class'=>'form-control', 'placeholder'=>'Post_date')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_title', 'Post_title:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('post_title', Input::old('post_title'), array('class'=>'form-control', 'placeholder'=>'Post_title')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_content', 'Post_content:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_content', Input::old('post_content'), array('class'=>'form-control', 'placeholder'=>'Post_content')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_status', 'Post_status:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_status', Input::old('post_status'), array('class'=>'form-control', 'placeholder'=>'Post_status')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('comment_status', 'Comment_status:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('comment_status', Input::old('comment_status'), array('class'=>'form-control', 'placeholder'=>'Comment_status')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('menu_order', 'Menu_order:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('menu_order', Input::old('menu_order'), array('class'=>'form-control', 'placeholder'=>'Menu_order')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_type', 'Post_type:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_type', Input::old('post_type'), array('class'=>'form-control', 'placeholder'=>'Post_type')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('comment_count', 'Comment_count:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('comment_count', Input::old('comment_count'), array('class'=>'form-control', 'placeholder'=>'Comment_count')) }}
            </div>
        </div>


<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Create', array('class' => 'btn btn-lg btn-primary')) }}
    </div>
</div>

{{ Form::close() }}

@stop

api/app/views/WpPosts/edit.blade.php
@extends('layouts.scaffold')

@section('main')

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <h1>Edit WpPost</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::model($WpPost, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('api.wp.posts.update', $WpPost->id))) }}

        <div class="form-group">
            {{ Form::label('post_author', 'Post_author:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_author', Input::old('post_author'), array('class'=>'form-control', 'placeholder'=>'Post_author')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_date', 'Post_date:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_date', Input::old('post_date'), array('class'=>'form-control', 'placeholder'=>'Post_date')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_title', 'Post_title:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('post_title', Input::old('post_title'), array('class'=>'form-control', 'placeholder'=>'Post_title')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_content', 'Post_content:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_content', Input::old('post_content'), array('class'=>'form-control', 'placeholder'=>'Post_content')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_status', 'Post_status:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_status', Input::old('post_status'), array('class'=>'form-control', 'placeholder'=>'Post_status')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('comment_status', 'Comment_status:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('comment_status', Input::old('comment_status'), array('class'=>'form-control', 'placeholder'=>'Comment_status')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('menu_order', 'Menu_order:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('menu_order', Input::old('menu_order'), array('class'=>'form-control', 'placeholder'=>'Menu_order')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('post_type', 'Post_type:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('post_type', Input::old('post_type'), array('class'=>'form-control', 'placeholder'=>'Post_type')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('comment_count', 'Comment_count:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('comment_count', Input::old('comment_count'), array('class'=>'form-control', 'placeholder'=>'Comment_count')) }}
            </div>
        </div>


<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Update', array('class' => 'btn btn-lg btn-primary')) }}
      {{ link_to_route('api.wp.posts.show', 'Cancel', $WpPost->ID, array('class' => 'btn btn-lg btn-default')) }}
    </div>
</div>

{{ Form::close() }}

@stop

api/app/views/WpPosts/index.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>All WpPosts</h1>

<p>{{ link_to_route('api.wp.posts.create', 'Add New WpPost', null, array('class' => 'btn btn-lg btn-success')) }}</p>

@if ($WpPosts->count())
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Post_author</th>
				<th>Post_date</th>
				<th>Post_title</th>
				<th>Post_content</th>
				<th>Post_status</th>
				<th>Comment_status</th>
				<th>Menu_order</th>
				<th>Post_type</th>
				<th>Comment_count</th>
				<th>&nbsp;</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($WpPosts as $WpPost)
				<tr>
					<td>{{{ $WpPost->post_author }}}</td>
					<td>{{{ $WpPost->post_date }}}</td>
					<td>{{{ $WpPost->post_title }}}</td>
					<td>{{{ $WpPost->post_content }}}</td>
					<td>{{{ $WpPost->post_status }}}</td>
					<td>{{{ $WpPost->comment_status }}}</td>
					<td>{{{ $WpPost->menu_order }}}</td>
					<td>{{{ $WpPost->post_type }}}</td>
					<td>{{{ $WpPost->comment_count }}}</td>
                    <td>
                        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('api.wp.posts.destroy', $WpPost->ID))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                        {{ link_to_route('api.wp.posts.edit', 'Edit', array($WpPost->ID), array('class' => 'btn btn-info')) }}
                    </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no WpPosts
@endif

@stop

api/app/views/WpPosts/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show WpPost</h1>

<p>{{ link_to_route('api.wp.posts.index', 'Return to All WpPosts', null, array('class'=>'btn btn-lg btn-primary')) }}</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Post_author</th>
				<th>Post_date</th>
				<th>Post_title</th>
				<th>Post_content</th>
				<th>Post_status</th>
				<th>Comment_status</th>
				<th>Menu_order</th>
				<th>Post_type</th>
				<th>Comment_count</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $WpPost->post_author }}}</td>
					<td>{{{ $WpPost->post_date }}}</td>
					<td>{{{ $WpPost->post_title }}}</td>
					<td>{{{ $WpPost->post_content }}}</td>
					<td>{{{ $WpPost->post_status }}}</td>
					<td>{{{ $WpPost->comment_status }}}</td>
					<td>{{{ $WpPost->menu_order }}}</td>
					<td>{{{ $WpPost->post_type }}}</td>
					<td>{{{ $WpPost->comment_count }}}</td>
                    <td>
                        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('api.wp.posts.destroy', $WpPost->ID))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                        {{ link_to_route('api.wp.posts.edit', 'Edit', array($WpPost->ID), array('class' => 'btn btn-info')) }}
                    </td>
		</tr>
	</tbody>
</table>

@stop

api/app/views/layouts/scaffold.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <style>
        body { padding-top: 20px; }
    </style>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            @if (Session::has('message'))
                <div class="flash alert">
                    <p>{{ Session::get('message') }}</p>
                </div>
            @endif

            @yield('main')

        </div>
    </div>
</div>

</body>
</html>